apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b6t00g88t-nodejs
  janus-idp.io/tekton: b6t00g88t-nodejs
  backstage.io/kubernetes-id: b6t00g88t-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: b6t00g88t-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
