apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b6t00g88t-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b6t00g88t-nodejs 
  name: b6t00g88t-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: b6t00g88t-nodejs 
